import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <header className="text-red-300">Header</header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
